### ISSUE TITLE
Video saved display frames before the camera was activated by a trigger

### ISSUE THREAD

**Issue by lalde** [AdaptiveMotorControlLab/Camera_Control#2]
Hello, 

I am using Camera Control to record behavioural videos during freely-behaving calcium imaging. My behavioural cameras (USB3 cameras from the Imaging Source) and imaging set-up are controlled by an Arduino. 

When I click on 'Initialize Camera', the image displayed is all black since the cameras haven't been triggered yet; it will show what the cameras are filming only when they are triggered by the Arduino script. 

My issue is that when I click on "Record On", it is writing these black frames in the video file. Similarly, when an experiment has ended, the Arduino stops sending TTL pulses to the cameras, so the image displayed are the last frame, frozen, and this is also written in the video file until I click 'Record: Off'.

Is there a way so that the frames that are written in the video file are only frames when the camera is active? Am I missing something in the GUI or write_camera_details file? 

Thank you for your time,
Lucie

**Comment by gkane26** [comment]
Hi Lucie,

Unfortunately this package wasn't designed to use with hardware (or software) triggered frame capture. When you click 'Initialize Camera', it will display whatever data it captures from the camera. Similarly, when you click 'Record On', it saves whatever data it captures. I don't think it will be possible to save only the frames when you are triggering without adding new features to this package. Also, I wouldn't recommend using a hardware trigger in combination with this package. One of the main reasons we developed this was to collect timestamps at the time we capture each frame. If you are using a hardware trigger, I worry that the timestamps recorded in software wouldn't be accurate, as the frame was actually captured at the time of the TTL pulse.

If you would like to continue to use CameraControl, is the trigger necessary? If the purpose of the TTL pulses for triggering is to synchronize the cameras with other signals, we have other means built in to the package to do so :)

**Comment by lalde** [comment]
Hi Gary, 

I see, thank you for the explanation! I am actually not using the timestamps output by the software, but instead using a logic analyzer capturing when the TTL pulses are being sent (among other signals). I am then using this to check the synchronization of the cameras with other signals. In that case, would you still advice against using the package since I will most probably always use a hardware trigger with it? 

What exactly are you referring to when mentioning other means built in to the package to sync the camera and get rid of the hardware trigger? 

Thanks again,
Lucie

**Comment by gkane26** [comment]
To synchronize our camera recordings with other signals recorded from another computer or data acquisition device, CameraControl can read in a TTL pulse (we've been using a NIDAQ card to do this since that's the data acquisition device we have lying around, but it should be pretty easy to use an arduino or other device for this purpose). To synchronize with a behavioral task, we can then compare the timestamps of recorded frames with a TTL pulse sent, e.g., at the start of every trial.

I don't want to necessarily advise against using this package, but we'd need to make some code changes. I don't think it would be too difficult to incorporate this, and I'd love to help more, but I unfortunately don't have the time to troubleshoot this at the moment. If you'd like to go down this route, I'd recommend using our [py36 branch](https://github.com/AdaptiveMotorControlLab/Camera_Control/tree/py36). It should operate the exact same, but we changed to python interface from the [pyicic package](https://github.com/morefigs/py-ic-imaging-control) to code based on/largely copied from The Imaging Source [code samples](https://github.com/TheImagingSource/IC-Imaging-Control-Samples), and updated everything to python3. Our modified version of this python interface is [here](https://github.com/AdaptiveMotorControlLab/Camera_Control/blob/py36/tisgrabber.py).

Unfortunately, The Imaging Source doesn't include using a trigger in their [python code samples](https://github.com/TheImagingSource/IC-Imaging-Control-Samples/tree/master/Python). The easiest thing to try might be to modify [this code block](https://github.com/AdaptiveMotorControlLab/Camera_Control/blob/051c7f7a17f8edb3158c1bb0d5b26d3a8802a358/camera_control_GUI.py#L227-L234). Maybe grab the image, if its blank (i.e. all zeros), then the camera probably hasn't been activated so don't write it to file. Alternatively, if the current image is equal to the previous image, then a new image hasn't been grabbed, so, again, don't write it to file? Not sure if that will work properly (are your images before the camera is activated all zeros?), but it would be a reasonably simple fix :)

**Comment by lalde** [comment]
No worries, with the state that the world is currently in, totally understandable if you have other priorities! I'm already very grateful that you took some time to look into it!

I was thinking about trimming the videos this way before doing further processing steps (if the frame is all zeros, ditch it), but it's even better if it would be possible to implement this at the image acquisition stage. Thank you for all the links and code snippets you referenced, these are good starting points :)
